---
title: "Initial exploration"
author: "Martine Wauben"
date: "01/05/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
```



```{r data prep}
# Loading and calculating data
data <- read.csv('GCR.csv') %>%
  dplyr::mutate(gradeAtHire = as.ordered(gradeAtHire),
         age = ageAtHire + tenure,
         gend_dept = paste(gender, department, sep = "_"),
         leaveYear = hireYear + tenure,
         term = ifelse(reason == "terminated", 1, 0))
str(data)
summary(data)

# Workforce over time:
all_years <- expand.grid(year = unique(c(data$hireYear, data$leaveYear)),
                         id = unique(data$id))
data_timeline <- dplyr::full_join(data, all_years, by = "id") %>%
  dplyr::filter(hireYear <= year & leaveYear >= year) %>%
  dplyr::group_by(id) %>%
  dplyr::mutate(reason = ifelse(year != max(year), NA, as.character(reason)),
                current = ifelse(year != max(year), TRUE, FALSE),
                term = ifelse(year != max(year), NA, as.numeric(term)),
                new = hireYear == year)

# Proportion of women in the workforce any year:
workforce_prop_timeline <- data_timeline %>%
  dplyr::group_by(year, gender) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::mutate(prop_workforce = n / sum(n)) %>%
  dplyr::filter(gender == "F") %>%
  dplyr::select(year, prop_workforce)


# People who have left:
data_left <- data[!data$current, ]
```


```{r visualise current workforce}
data_current <- data[data$current, ]
summary(data_current)
# Age by gender
ggplot(data_current, aes(x = gender, y = age))+
  geom_violin()
# Tenure by gender
ggplot(data_current, aes(x = gender, y = tenure))+
  geom_violin()
# Department by gender
ggplot(data_current, aes(x = gender, y = department))+
  geom_bin2d()
# Grade at hire by gender
ggplot(data_current, aes(x = gender, y = gradeAtHire))+
  geom_bin2d()
# Tenure by department
ggplot(data_current, aes(x = department, y = tenure))+
  geom_boxplot()
# Age by department
ggplot(data_current, aes(x = department, y = age))+
  geom_violin()

# Age by gender and department
ggplot(data_current, aes(x = gend_dept, y = tenure))+
  geom_violin()
# Mainly the administrative dept has much less experienced women than men, much more similar in operations
ggplot(data_current, aes(x = gend_dept, y = age))+
  geom_violin()
ggplot(data_current, aes(x = gend_dept, y = ageAtHire))+
  geom_violin()
```


```{r visualise leavers}
# Were there peak leaving years?
hist(data_left$leaveYear, breaks = length(unique(data_left$leaveYear)))
# There were some spikes: 1986, 2002, 2008/9
# Were women overrepresented in those years?
data_years <- data_left %>%
  dplyr::group_by(leaveYear, gender) %>%
  dplyr::summarise(n = n()) %>%
  tidyr::spread(gender, n) %>%
  dplyr::mutate(F_prop = `F` / (`F` + `M`))
ggplot(data_years, aes(x = leaveYear, y = F_prop))+
  geom_bar(stat = "identity")
# Not noticeably more women leaving in those years as a proportion of everyone leaving that year

# Age by gender
ggplot(data_left, aes(x = gender, y = age))+
  geom_violin()
# Tenure by gender
ggplot(data_left, aes(x = gender, y = tenure))+
  geom_violin()
# Department by gender
ggplot(data_left, aes(x = gender, y = department))+
  geom_bin2d()
# Grade at hire by gender
ggplot(data_left, aes(x = gender, y = gradeAtHire))+
  geom_bin2d()
# Tenure by department
ggplot(data_left, aes(x = department, y = tenure))+
  geom_boxplot()
# Age by department
ggplot(data_left, aes(x = department, y = age))+
  geom_violin()

# Age by gender and department
ggplot(data_left, aes(x = gend_dept, y = tenure))+
  geom_violin()
# Mainly the administrative dept has much less experienced women than men, much more similar in operations
ggplot(data_left, aes(x = gend_dept, y = age))+
  geom_violin()
ggplot(data_left, aes(x = gend_dept, y = ageAtHire))+
  geom_violin()
```


```{r workforce in any year}
data_dept_timeline <- data_timeline  %>%
  dplyr::group_by(year, department, gender) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::mutate(prop = n / sum(n)) %>%
  dplyr::filter(gender == "F") %>%
  left_join(., workforce_prop_timeline, by = "year")
ggplot(data_dept_timeline, aes(x = year, y = prop, colour = department))+
  geom_line()+
  geom_smooth(alpha = 0.25)+
  geom_line(aes(x = year, y = prop_workforce), 
              colour = "red")+
  labs(title = "Proportion of female workforce over time",
       x = "Year",
       y = "Proportion of workers that were female",
       colour = "Department",
       subtitle = "GCR overall proportion in shown in red")
```

```{r Reasons for leaving}
# Reasons for leaving by gender
ggplot(data_left, aes(x = gender, y = reason))+
  geom_bin2d()
# Reasons for leaving by gender and department
ggplot(data_left, aes(x = gend_dept, y = reason))+
  geom_bin2d()

workforce_dept_prop_timeline <- data_timeline %>%
  dplyr::group_by(year, department, gender) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::mutate(prop_workforce = n / sum(n)) %>%
  dplyr::filter(gender == "F") %>%
  dplyr::select(leaveYear = year, department, prop_workforce)

all_reasons <- expand.grid(leaveYear = unique(data_left$leaveYear),
                           department = unique(data_left$department),
                           reason = unique(data_left$reason),
                           gender = unique(data_left$gender))
data_reasons <- data_left %>%
  dplyr::group_by(leaveYear, department, reason, gender) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::ungroup() %>%
  dplyr::full_join(., all_reasons, 
                   by = c("leaveYear", "department", "reason", "gender")) %>%
  dplyr::mutate(n = ifelse(is.na(n), 0, n)) %>%
  dplyr::group_by(leaveYear, department, reason) %>%
  dplyr::mutate(tot = sum(n)) %>%
  dplyr::ungroup() %>%
  dplyr::filter(gender == "F") %>%
  dplyr::mutate(prop = ifelse(tot > 0,
                              n / tot, 0)) %>%
  dplyr::left_join(., workforce_dept_prop_timeline, 
                   by = c("leaveYear", "department")) %>%
  dplyr::arrange(leaveYear, department, reason, gender)


ggplot(data_reasons, aes(x = leaveYear, y = prop, colour = reason))+
  geom_line(alpha = 0.5)+
  geom_smooth(se = FALSE)+
  geom_line(aes(x = leaveYear, y = prop_workforce), 
            colour = "red")+
  facet_wrap(department~reason)+
  labs(title = "Women as a % of all who leave for each reason",
       x = "Year of leaving",
       y = "Proportion of women",
       subtitle = "Department's overall proportion of women shown in red")

# Significant association between gender and being terminated?
chisq.test(table(data$gender, data$term))
```



```{r characteristics of terminated people}
library("graphics")
data_dept <- as.table(as.matrix(table(data_left$department, data_left$term)))
mosaicplot(data_dept, shade = TRUE, las=2, main = "Department")
data_ageH <- as.table(as.matrix(table(data_left$ageAtHire, data_left$term)))
mosaicplot(data_ageH, shade = TRUE, las=2, main = "ageAtHire")
data_ageL <- as.table(as.matrix(table(data_left$age, data_left$term)))
mosaicplot(data_ageL, shade = TRUE, las=2, main = "ageWhenLeft")
data_year <- as.table(as.matrix(table(data_left$hireYear, data_left$term)))
mosaicplot(data_year, shade = TRUE, las=2, main = "hireYear")
data_leave <- as.table(as.matrix(table(data_left$leaveYear, data_left$term)))
mosaicplot(data_leave, shade = TRUE, las=2, main = "leaveYear")
# data_ten <- as.table(as.matrix(data_left$tenure, data_left$term))
# mosaicplot(data_ten, shade = TRUE, las=2, main = "Tenure")
data_gend <- as.table(as.matrix(table(data_left$gender, data_left$term)))
mosaicplot(data_gend, shade = TRUE, las=2, main = "Gender")
data_grade <- as.table(as.matrix(table(data_left$gradeAtHire, data_left$term)))
mosaicplot(data_grade, shade = TRUE, las=2, main = "GradeAtHire")

summary(aov(term ~ gradeAtHire * department * gender * ageAtHire * hireYear, data = data_left))
# Main effects of department, gender, and hireYear, but 3-way interaction of GradeAtHire, gender and HireYear


(data_term_leave <- data_left %>%
  dplyr::filter(leaveYear < max(hireYear)) %>%
  dplyr::group_by(leaveYear, department, gender) %>%
  dplyr::summarise(left = n(),
                   terminated = sum(term),
                   prop_term = sum(term) / n(),
                   m_ageAtHire = mean(ageAtHire),
                   sd_ageAtHire = sd(ageAtHire, na.rm = T),
                   m_ageWhenLeft = mean(age),
                   sd_ageWhenLeft = sd(age),
                   m_tenure = mean(tenure),
                   sd_tenure = sd(tenure),
                   m_gradeAtHire = mean(as.numeric(gradeAtHire)),
                   sd_gradeAtHire = sd(as.numeric(gradeAtHire))))


ggplot(data_term_leave, aes(x = leaveYear, y = prop_term, colour = gender))+
  geom_line(alpha = 0.5)+
  geom_smooth(se = FALSE)+
  facet_wrap(~department)+
  labs(title = "Of those who left, the proportion terminated",
       x = "Year left",
       y = "Proportion terminated",
       subtitle = "By department, gender and year they left")

data_term_hire <- data_left %>%
  dplyr::filter(hireYear < max(hireYear)) %>%
  dplyr::group_by(hireYear, department, gender) %>%
  dplyr::summarise(left = n(),
                   terminated = sum(term),
                   prop_term = sum(term) / n(),
                   m_ageAtHire = mean(ageAtHire),
                   sd_ageAtHire = sd(ageAtHire, na.rm = T),
                   m_ageWhenLeft = mean(age),
                   sd_ageWhenLeft = sd(age),
                   m_tenure = mean(tenure),
                   sd_tenure = sd(tenure),
                   m_gradeAtHire = mean(as.numeric(gradeAtHire)),
                   sd_gradeAtHire = sd(as.numeric(gradeAtHire)))


ggplot(data_term_hire, aes(x = hireYear, y = prop_term, colour = gender))+
  geom_line(alpha = 0.5)+
  geom_smooth(se = FALSE)+
  facet_wrap(~department)+
  labs(title = "Of those who left, the proportion terminated",
       x = "Year hired",
       y = "Proportion terminated",
       subtitle = "By department, gender and year they were hired")

```


```{r rate of termination for men and women}
data_rate <- data_timeline %>%
  dplyr::group_by(year, department, gender) %>%
  dplyr::summarise(workforce = n(),
                   left = sum(current != TRUE),
                   joined = sum(new == TRUE),
                   terminated = sum(term, na.rm = T)) %>%
  dplyr::mutate(joining_rate = joined / workforce,
                leaving_rate = left / workforce,
                termination_rate = terminated / workforce,
                term_leaving_rate = terminated / left)

ggplot(data_rate, aes(x = year, y = termination_rate, colour = gender))+
  geom_line(alpha = 0.5)+
  geom_smooth(se = FALSE)+
  facet_wrap(~department)
```


